//! Port of jdt.ls `CodeLensHandler`: references and implementations code
//! lenses (`java.referencesCodeLens.enabled`, `java.implementationCodeLens`),
//! resolved to `java.show.references` / `java.show.implementations`
//! commands with `[uri, position, locations]` arguments.
//!
//! The lenses are collected in Rust from the tree-sitter tree with the Java
//! model's rules (types and methods only, children before their type,
//! generated Lombok members skipped); resolution uses the semantic index.

use super::java_element;
use super::preferences;
use super::semantic::{Elem, Semantic};
use crate::analysis::dispatcher::Dispatcher;
use crate::document_store::DocumentStore;
use serde_json::{json, Value};
use tower_lsp::lsp_types::{CodeLens, Command, Location, Position, Range, Url};
use tree_sitter::Node;

pub const REFERENCES_TYPE: &str = "references";
pub const IMPLEMENTATION_TYPE: &str = "implementations";
const JAVA_SHOW_REFERENCES_COMMAND: &str = "java.show.references";
const JAVA_SHOW_IMPLEMENTATIONS_COMMAND: &str = "java.show.implementations";

/// `CodeLensHandler.getCodeLensSymbols`.
pub fn code_lenses(store: &DocumentStore, uri: &Url) -> Vec<CodeLens> {
    if !preferences::code_lens_enabled() {
        return Vec::new();
    }
    let Some(state) = store.get(uri) else { return Vec::new() };
    let Some(tree) = state.tree.clone() else { return Vec::new() };
    let text = state.content_string();
    drop(state);
    let mut c = Collector { text: &text, uri: uri.as_str(), lenses: Vec::new() };
    let root = tree.root_node();
    let mut implicit_members = Vec::new();
    let mut cur = root.walk();
    for child in root.named_children(&mut cur) {
        if is_type(child) {
            c.collect_type(child);
        } else if matches!(child.kind(), "method_declaration") {
            implicit_members.push(child);
        }
    }
    // An implicitly declared (unnamed) class: its members, but no lens on the class.
    for m in implicit_members {
        c.member(m, None);
    }
    c.lenses
}

struct Collector<'a> {
    text: &'a str,
    uri: &'a str,
    lenses: Vec<CodeLens>,
}

fn is_type(n: Node) -> bool {
    matches!(
        n.kind(),
        "class_declaration" | "interface_declaration" | "enum_declaration" | "record_declaration" | "annotation_type_declaration"
    )
}

fn is_method(n: Node) -> bool {
    matches!(
        n.kind(),
        "method_declaration" | "constructor_declaration" | "compact_constructor_declaration" | "annotation_type_element_declaration"
    )
}

impl<'a> Collector<'a> {
    fn collect_type(&mut self, ty: Node) {
        if let Some(body) = ty.child_by_field_name("body") {
            for member in body_members(body) {
                if is_type(member) {
                    self.collect_type(member);
                } else if is_method(member) {
                    self.member(member, Some(ty));
                }
            }
        }
        // the type itself
        let Some(name) = ty.child_by_field_name("name") else { return };
        let range = self.range(name);
        if preferences::references_code_lens_enabled() {
            self.push(REFERENCES_TYPE, range);
        }
        let imp = preferences::implementations_code_lens();
        if imp == "all" || imp == "types" {
            self.push(IMPLEMENTATION_TYPE, range);
        }
    }

    fn member(&mut self, m: Node, parent: Option<Node>) {
        if is_hidden_generated(m, self.text) {
            return;
        }
        let name = if m.kind() == "compact_constructor_declaration" {
            m.child_by_field_name("name")
        } else {
            m.child_by_field_name("name")
        };
        let Some(name) = name else { return };
        if let Some(p) = parent {
            if let Some(tn) = p.child_by_field_name("name") {
                // generated byte code (Lombok) reports the type's name range
                let (to, tl) = (tn.start_byte(), tn.end_byte() - tn.start_byte());
                let mo = name.start_byte();
                if mo < to || (mo >= to && mo <= to + tl) {
                    return;
                }
            }
        }
        let range = self.range(name);
        if preferences::references_code_lens_enabled() {
            self.push(REFERENCES_TYPE, range);
        }
        let imp = preferences::implementations_code_lens();
        if imp == "all" || imp == "methods" {
            self.push(IMPLEMENTATION_TYPE, range);
        }
    }

    fn range(&self, n: Node) -> Range {
        Range { start: position(self.text, n.start_byte()), end: position(self.text, n.end_byte()) }
    }

    fn push(&mut self, kind: &str, range: Range) {
        let data = json!([self.uri, { "line": range.start.line, "character": range.start.character }, kind]);
        let lens = CodeLens { range, command: None, data: Some(data) };
        if !self.lenses.iter().any(|l| l.range == lens.range && l.data == lens.data) {
            self.lenses.push(lens);
        }
    }
}

/// The member declarations of a type body (enum bodies keep theirs in
/// `enum_body_declarations`).
fn body_members(body: Node) -> Vec<Node> {
    let mut out = Vec::new();
    let mut cur = body.walk();
    for child in body.named_children(&mut cur) {
        if child.kind() == "enum_body_declarations" {
            let mut c2 = child.walk();
            out.extend(child.named_children(&mut c2));
        } else {
            out.push(child);
        }
    }
    out
}

/// `JDTUtils.isHiddenGeneratedElement`: `@javax.annotation.Generated` /
/// `@javax.annotation.processing.Generated` (as written) with a `value` of
/// `"lombok"`.
fn is_hidden_generated(m: Node, text: &str) -> bool {
    let mut cur = m.walk();
    let Some(mods) = m.named_children(&mut cur).find(|c| c.kind() == "modifiers") else { return false };
    let mut c2 = mods.walk();
    for ann in mods.named_children(&mut c2) {
        if ann.kind() != "annotation" {
            continue;
        }
        let Some(name) = ann.child_by_field_name("name") else { continue };
        let name = &text[name.byte_range()];
        if name != "javax.annotation.Generated" && name != "javax.annotation.processing.Generated" {
            continue;
        }
        let Some(args) = ann.child_by_field_name("arguments") else { continue };
        let mut c3 = args.walk();
        for arg in args.named_children(&mut c3) {
            let value = if arg.kind() == "element_value_pair" {
                let key = arg.child_by_field_name("key").map(|k| &text[k.byte_range()]);
                if key != Some("value") {
                    continue;
                }
                match arg.child_by_field_name("value") {
                    Some(v) => v,
                    None => continue,
                }
            } else {
                arg
            };
            if string_values(value, text).iter().any(|v| v == "lombok") {
                return true;
            }
            if arg.kind() != "element_value_pair" {
                break;
            }
        }
    }
    false
}

fn string_values(v: Node, text: &str) -> Vec<String> {
    match v.kind() {
        "string_literal" => {
            let s = &text[v.byte_range()];
            vec![s.trim_matches('"').to_owned()]
        }
        "element_value_array_initializer" => {
            let mut out = Vec::new();
            let mut cur = v.walk();
            for c in v.named_children(&mut cur) {
                out.extend(string_values(c, text));
            }
            out
        }
        _ => Vec::new(),
    }
}

/// LSP position (UTF-16 columns) of a byte offset.
pub fn position(text: &str, byte: usize) -> Position {
    let byte = byte.min(text.len());
    let before = &text[..byte];
    let line_start = before.rfind('\n').map_or(0, |i| i + 1);
    let line = before.matches('\n').count() as u32;
    let character = before[line_start..].encode_utf16().count() as u32;
    Position { line, character }
}

/// `CodeLensHandler.resolve`.
pub async fn resolve(dispatcher: &Dispatcher, mut lens: CodeLens) -> CodeLens {
    let Some(Value::Array(data)) = lens.data.clone() else { return lens };
    let kind = data.get(2).and_then(Value::as_str).unwrap_or("").to_owned();
    let position: Position = data
        .get(1)
        .and_then(|p| serde_json::from_value(p.clone()).ok())
        .unwrap_or(lens.range.start);
    let uri = data.get(0).and_then(Value::as_str).unwrap_or("").to_owned();
    let (label, command) = match kind.as_str() {
        REFERENCES_TYPE => ("reference", JAVA_SHOW_REFERENCES_COMMAND),
        IMPLEMENTATION_TYPE => ("implementation", JAVA_SHOW_IMPLEMENTATIONS_COMMAND),
        _ => return lens,
    };
    let mut locations: Vec<Location> = Vec::new();
    if let Ok(url) = Url::parse(&uri) {
        if dispatcher.store.contains(&url) || dispatcher.store.get(&url).is_some() {
            let sem = Semantic::new(dispatcher).await;
            if let Some((sel, _)) = sem.select(&url, position).await {
                if let Some(element) = sel.select.first() {
                    if kind == REFERENCES_TYPE {
                        locations = find_references(&sem, element).await;
                    } else if element.is_type() || element.is_method_like() {
                        locations = find_implementations(&sem, element).await;
                    }
                }
            }
        }
    }
    let size = locations.len();
    let title = format!("{size} {label}{}", if size == 1 { "" } else { "s" });
    lens.command = Some(Command {
        title,
        command: command.to_owned(),
        arguments: Some(vec![
            Value::String(uri),
            serde_json::to_value(position).unwrap_or(Value::Null),
            serde_json::to_value(&locations).unwrap_or(Value::Array(Vec::new())),
        ]),
    });
    lens
}

async fn find_references(sem: &Semantic<'_>, element: &Elem) -> Vec<Location> {
    let (matches, _) = sem.references(element, "references").await;
    let exclude_tests = preferences::search_scope_main();
    let ws = sem.dispatcher.workspace.read().unwrap_or_else(|e| e.into_inner()).clone();
    matches
        .into_iter()
        .filter(|m| m.accurate)
        .filter(|m| !exclude_tests || !is_test_source(&ws, &m.uri))
        .filter_map(|m| Some(Location { uri: Url::parse(&m.uri).ok()?, range: m.range.to_lsp() }))
        .collect()
}

pub fn is_test_source(ws: &crate::project::Workspace, uri: &str) -> bool {
    let Some(path) = Url::parse(uri).ok().and_then(|u| crate::project::uri_to_path(&u)) else { return false };
    ws.project_for_path(&path)
        .and_then(|p| p.source_folder_for(&path))
        .is_some_and(|sf| sf.is_test)
}

async fn find_implementations(sem: &Semantic<'_>, element: &Elem) -> Vec<Location> {
    let ws = sem.dispatcher.workspace.read().unwrap_or_else(|e| e.into_inner()).clone();
    let project = java_element::project_of(&ws, element.uri.as_deref());
    let use_default = element.is_type() && element.fqn.as_deref() == Some("java.lang.Object");
    let mut out = Vec::new();
    for mut imp in sem.implementations(element).await {
        sem.complete(&mut imp).await;
        let loc = if imp.from_source {
            java_element::name_location(&imp, &project)
        } else if preferences::class_file_contents_supported() {
            java_element::full_location(&imp, &project)
        } else {
            None
        };
        if let Some(mut loc) = loc {
            if use_default {
                loc.range = java_element::zero_range();
            }
            out.push(loc);
        }
    }
    out
}
