//! Attached Javadoc (HTML from a Javadoc jar or folder): port of JDT's
//! `JavadocContents` / `JavadocContents17` slicing for type and field
//! documentation (`BinaryType.getAttachedJavadoc`, `BinaryField.getAttachedJavadoc`).

const ANCHOR_PREFIX_END: &str = "\"";
const ANCHOR_PREFIX_START: &str = "<A NAME=\"";
const ANCHOR_PREFIX_START_2: &str = "<A ID=\"";
const ANCHOR_SUFFIX: &str = "</A>";
const CONSTRUCTOR_DETAIL: &str = "<!-- ========= CONSTRUCTOR DETAIL ======== -->";
const CONSTRUCTOR_SUMMARY: &str = "<!-- ======== CONSTRUCTOR SUMMARY ======== -->";
const FIELD_DETAIL: &str = "<!-- ============ FIELD DETAIL =========== -->";
const FIELD_SUMMARY: &str = "<!-- =========== FIELD SUMMARY =========== -->";
const ENUM_CONSTANT_SUMMARY: &str = "<!-- =========== ENUM CONSTANT SUMMARY =========== -->";
const ANNOTATION_TYPE_REQUIRED_MEMBER_SUMMARY: &str = "<!-- =========== ANNOTATION TYPE REQUIRED MEMBER SUMMARY =========== -->";
const ANNOTATION_TYPE_OPTIONAL_MEMBER_SUMMARY: &str = "<!-- =========== ANNOTATION TYPE OPTIONAL MEMBER SUMMARY =========== -->";
const END_OF_CLASS_DATA: &str = "<!-- ========= END OF CLASS DATA ========= -->";
const METHOD_DETAIL: &str = "<!-- ============ METHOD DETAIL ========== -->";
const METHOD_SUMMARY: &str = "<!-- ========== METHOD SUMMARY =========== -->";
const NESTED_CLASS_SUMMARY: &str = "<!-- ======== NESTED CLASS SUMMARY ======== -->";
const SEPARATOR_START: &str = "<!-- =";
const START_OF_CLASS_DATA: &str = "<!-- ======== START OF CLASS DATA ======== -->";
const P: &str = "<P>";
const PACKAGE_DESCRIPTION_START: &str = "name=\"package_description\"";
const PACKAGE_DESCRIPTION_START2: &str = "name=\"package.description\"";
const PACKAGE_DESCRIPTION_START3: &str = "<div class=\"contentContainer\">";
const H2_PREFIX: &str = "<H2";
const H2_SUFFIX: &str = "</H2>";
const BOTTOM_NAVBAR: &str = "<!-- ======= START OF BOTTOM NAVBAR ====== -->";
const DIV_CLASS_BLOCK: &str = "<DIV CLASS=\"BLOCK\">";
const GENERATED_BY_JAVADOC: &str = "Generated by javadoc";
const SECTION_PREFIX_START: &str = "<section class=\"detail\" id=\"";
const SECTION_SUFFIX: &str = "</section>";

/// A Javadoc range, or JDT's `UNKNOWN_FORMAT` (a `JavaModelException`).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Range {
    Known(usize, usize),
    Unknown,
}

pub struct JavadocContents {
    content: Vec<char>,
    lower: Vec<char>,
    v17: bool,
    children_start: usize,
}

fn lower(c: char) -> char {
    c.to_lowercase().next().unwrap_or(c)
}

impl JavadocContents {
    /// `ExternalJavadocSupport.forHtml`
    pub fn for_html(html: &str) -> Self {
        let content: Vec<char> = html.chars().collect();
        let lower_content = content.iter().map(|&c| lower(c)).collect();
        Self { v17: guess_version(html) >= 17, content, lower: lower_content, children_start: 0 }
    }

    /// `CharOperation.indexOf(toBeFound, array, false, start[, end])`
    fn index_of(&self, needle: &str, start: usize, end: Option<usize>) -> Option<usize> {
        let n: Vec<char> = needle.chars().map(lower).collect();
        let end = end.unwrap_or(self.lower.len()).min(self.lower.len());
        if n.is_empty() || start > end || end - start < n.len() {
            return None;
        }
        (start..=end - n.len()).find(|&i| self.lower[i..i + n.len()] == n[..])
    }

    fn prefix_equals(&self, prefix: &str, at: usize) -> bool {
        let p: Vec<char> = prefix.chars().map(lower).collect();
        at + p.len() <= self.lower.len() && self.lower[at..at + p.len()] == p[..]
    }

    fn slice(&self, r: Range) -> Option<String> {
        match r {
            Range::Known(s, e) if s <= e => Some(self.content[s..e].iter().collect()),
            _ => None,
        }
    }

    /// `getTypeDoc()`; `None` for an unknown format too (the exception is
    /// swallowed by `CoreJavadocAccess.getHTMLContent`).
    pub fn type_doc(&mut self, is_enum: bool, is_annotation: bool) -> Option<String> {
        let r = self.compute_type_range(is_enum, is_annotation);
        self.slice(r)
    }

    fn compute_type_range(&mut self, is_enum: bool, is_annotation: bool) -> Range {
        let Some(start_of_class_data) = self.index_of(START_OF_CLASS_DATA, 0, None) else { return Range::Unknown };
        let Some(next_separator) = self.index_of(SEPARATOR_START, start_of_class_data, None) else { return Range::Unknown };
        let mut next_summary = self.index_of(NESTED_CLASS_SUMMARY, next_separator, None);
        if next_summary.is_none() && is_enum {
            next_summary = self.index_of(ENUM_CONSTANT_SUMMARY, next_separator, None);
        }
        if next_summary.is_none() && is_annotation {
            next_summary = self
                .index_of(ANNOTATION_TYPE_REQUIRED_MEMBER_SUMMARY, next_separator, None)
                .or_else(|| self.index_of(ANNOTATION_TYPE_OPTIONAL_MEMBER_SUMMARY, next_separator, None));
        }
        for marker in [FIELD_SUMMARY, CONSTRUCTOR_SUMMARY, METHOD_SUMMARY] {
            if next_summary.is_none() {
                next_summary = self.index_of(marker, next_separator, None);
            }
        }
        let next_summary = match next_summary {
            None => self.index_of(END_OF_CLASS_DATA, next_separator, None),
            Some(i) => {
                self.children_start = i + 1;
                Some(i)
            }
        };
        let Some(next_summary) = next_summary else { return Range::Unknown };
        // Cut off the type hierarchy (bug 119844)
        let mut start = start_of_class_data + START_OF_CLASS_DATA.chars().count();
        let first_paragraph = self.index_of(P, start, Some(next_summary));
        let first_div = self.index_of(DIV_CLASS_BLOCK, start, Some(next_summary));
        let mut after_hierarchy = next_summary;
        if let Some(p) = first_paragraph.filter(|&p| p < after_hierarchy) {
            after_hierarchy = p;
        }
        if let Some(d) = first_div.filter(|&d| d < after_hierarchy) {
            after_hierarchy = d;
        }
        if after_hierarchy != next_summary {
            start = after_hierarchy;
        }
        Range::Known(start, next_summary)
    }

    /// `getPackageDoc()`
    pub fn package_doc(&self) -> Option<String> {
        let mut index = self
            .index_of(PACKAGE_DESCRIPTION_START2, 0, None)
            .or_else(|| self.index_of(PACKAGE_DESCRIPTION_START, 0, None));
        if let Some(i) = index {
            let i = self.index_of(ANCHOR_SUFFIX, i, None)?;
            index = Some(i);
            if let Some(start) = self.index_of(H2_PREFIX, i, None) {
                if let Some(start) = self.index_of(H2_SUFFIX, start, None) {
                    index = Some(start + H2_SUFFIX.chars().count());
                }
            }
        } else {
            index = self.index_of(PACKAGE_DESCRIPTION_START3, 0, None);
        }
        let index = index?;
        let end = self.index_of(BOTTOM_NAVBAR, index, None).unwrap_or(self.content.len().saturating_sub(1));
        self.slice(Range::Known(index, end))
    }

    /// `getFieldDoc(field)`
    pub fn field_doc(&mut self, name: &str) -> Option<String> {
        let last = self.index_of(SEPARATOR_START, self.children_start, None).unwrap_or(self.children_start);
        let field_details = self.index_of(FIELD_DETAIL, last, None);
        let last = field_details.unwrap_or(last);
        let constructor_details = self.index_of(CONSTRUCTOR_DETAIL, last, None);
        let last = constructor_details.unwrap_or(last);
        let method_details = self.index_of(METHOD_DETAIL, last, None);
        let last = method_details.unwrap_or(last);
        let end_of_class_data = self.index_of(END_OF_CLASS_DATA, last, None);
        let fields_bottom = constructor_details.or(method_details).or(end_of_class_data);
        let anchor = format!("{name}{ANCHOR_PREFIX_END}");
        let from = if field_details.is_none() || fields_bottom.is_none() { self.children_start } else { field_details.unwrap() };
        let r = self.compute_child_range(&anchor, from, fields_bottom);
        r.and_then(|r| self.slice(r))
    }

    /// `getAnchorIndex(from)`: (index, prefix length)
    fn anchor_index(&self, from: usize) -> Option<(usize, usize)> {
        if self.v17 {
            return self.index_of(SECTION_PREFIX_START, from, None).map(|i| (i, SECTION_PREFIX_START.chars().count()));
        }
        self.index_of(ANCHOR_PREFIX_START, from, None)
            .map(|i| (i, ANCHOR_PREFIX_START.chars().count()))
            .or_else(|| self.index_of(ANCHOR_PREFIX_START_2, from, None).map(|i| (i, ANCHOR_PREFIX_START_2.chars().count())))
    }

    fn compute_child_range(&self, anchor: &str, mut from: usize, bottom: Option<usize>) -> Option<Range> {
        while let Some((index, len)) = self.anchor_index(from) {
            if bottom.is_some_and(|b| index >= b) {
                break;
            }
            from = index + 1;
            let anchor_end_start = index + len;
            if self.prefix_equals(anchor, anchor_end_start) {
                return Some(self.child_range_at(anchor_end_start, anchor, bottom));
            }
        }
        None
    }

    fn child_range_at(&self, anchor_end_start: usize, anchor: &str, bottom: Option<usize>) -> Range {
        let Some(bottom) = bottom else { return Range::Unknown };
        let anchor_len = anchor.chars().count();
        if self.v17 {
            let start = anchor_end_start + anchor_len + 1;
            return match self.index_of(SECTION_SUFFIX, start, None) {
                Some(end) => Range::Known(start, end.min(bottom)),
                None => Range::Unknown,
            };
        }
        match self.index_of(ANCHOR_SUFFIX, anchor_end_start + anchor_len, None) {
            Some(end_link) => {
                let next = self.anchor_index(end_link).map(|(i, _)| i);
                let start = end_link + ANCHOR_SUFFIX.chars().count();
                let end = match next {
                    None => bottom,
                    Some(n) => n.min(bottom),
                };
                Range::Known(start, end)
            }
            None => Range::Unknown,
        }
    }
}

/// `ExternalJavadocSupport.guessVersion`
fn guess_version(html: &str) -> i32 {
    if html.trim().is_empty() {
        return -1;
    }
    let Some(header) = html.find(GENERATED_BY_JAVADOC) else { return -1 };
    let Some(open) = html[header..].find('(') else { return -1 };
    let start = header + open + 1;
    let Some(close) = html[start..].find(')') else { return -1 };
    let mut version = &html[start..start + close];
    if let Some(dot) = version.find('.').filter(|&d| d > 0) {
        version = &version[..dot];
    }
    version.parse().unwrap_or(-1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn type_doc_old_format() {
        let html = "<HTML><!-- ======== START OF CLASS DATA ======== -->\n<H2>Class X</H2>\n<PRE>java.lang.Object</PRE>\n<P>\nThe doc.\n<P>\n<!-- =========== FIELD SUMMARY =========== -->\n";
        let mut c = JavadocContents::for_html(html);
        assert_eq!(c.type_doc(false, false).as_deref(), Some("<P>\nThe doc.\n<P>\n"));
    }
}
