//! Extracts the embedded ecj-bridge JAR to a temp file on first use.

// Generated by build.rs — contains `pub static ECJ_JAR_BYTES: &[u8]`
include!(concat!(env!("OUT_DIR"), "/ecj_jar_bytes.rs"));

use anyhow::{anyhow, Result};
use once_cell::sync::OnceCell;
use std::path::{Path, PathBuf};

static JAR_PATH: OnceCell<PathBuf> = OnceCell::new();
static SOCKET_PATH: OnceCell<PathBuf> = OnceCell::new();

/// FNV-1a hash of the embedded JAR bytes — used to version filenames so that
/// stale files from old builds are never accidentally reused.
fn jar_hash() -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for &b in ECJ_JAR_BYTES {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

/// Unix socket path for the shared ecj-bridge daemon process.
/// Path: `<tmp>/ecj-bridge-<hash>.sock`
pub fn socket_path() -> &'static Path {
    SOCKET_PATH
        .get_or_init(|| {
            std::env::temp_dir().join(format!("ecj-bridge-{:016x}.sock", jar_hash()))
        })
        .as_path()
}

/// Returns the path to the extracted JAR, extracting it on first call.
///
/// The JAR is written to `<tmp>/jdtls-ecj-<hash>.jar` and reused across
/// invocations (if the file already exists with the right size it is not
/// re-extracted, making cold-start fast).
pub fn jar_path() -> Result<&'static Path> {
    JAR_PATH
        .get_or_try_init(extract)
        .map(|p| p.as_path())
}

fn extract() -> Result<PathBuf> {
    if ECJ_JAR_BYTES.is_empty() {
        return Err(anyhow!(
            "ecj-bridge JAR was not embedded at compile time. \
             Run `mvn -f ecj-bridge/pom.xml package -DskipTests` then rebuild."
        ));
    }

    let tmp = std::env::temp_dir().join(format!("jdtls-ecj-{:016x}.jar", jar_hash()));

    if tmp.exists() && tmp.metadata().map(|m| m.len()).unwrap_or(0) == ECJ_JAR_BYTES.len() as u64 {
        // Already extracted from a previous run — reuse it.
        return Ok(tmp);
    }

    std::fs::write(&tmp, ECJ_JAR_BYTES)
        .map_err(|e| anyhow!("failed to extract ecj-bridge JAR to {}: {e}", tmp.display()))?;

    Ok(tmp)
}
